os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master
    - develop

before_script:
  - env | sort
  - dir="images/${VERSION}/${VARIANT}"
  - export TAG=travis
  - export VCS_REF=`git rev-parse --short HEAD`
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - export IMAGE_NAME=docker-dokos-ext

script:
  - cd "$dir"
  # Test containers build
  - docker-compose -f docker-compose.test.yml build
  - docker images
  # Test containers run
  - travis_retry docker-compose -f docker-compose.test.yml up -d
  - docker-compose -f docker-compose.test.yml logs -f "sut"
  - docker-compose -f docker-compose.test.yml ps
  - docker-compose -f docker-compose.test.yml logs "dokos-db"
  - docker-compose -f docker-compose.test.yml ps "dokos-db" | grep "Up"
  - docker-compose -f docker-compose.test.yml logs "dokos"
  - docker-compose -f docker-compose.test.yml ps "dokos" | grep "Up"
  - docker-compose -f docker-compose.test.yml ps "sut" | grep "Exit 0"
  # Test containers can be dropped and restarted
  - docker-compose -f docker-compose.test.yml down
  - travis_retry docker-compose -f docker-compose.test.yml up -d
  - docker-compose -f docker-compose.test.yml logs "sut"
  - docker-compose -f docker-compose.test.yml ps
  - docker-compose -f docker-compose.test.yml logs "dokos-db"
  - docker-compose -f docker-compose.test.yml ps "dokos-db" | grep "Up"
  - docker-compose -f docker-compose.test.yml logs "dokos"
  - docker-compose -f docker-compose.test.yml ps "dokos" | grep "Up"
  - docker-compose -f docker-compose.test.yml ps "sut" | grep "Exit 0"

notifications:
  email: false

env: # Environments
  - VERSION=develop VARIANT=alpine3.12 DATABASE=postgres
  - VERSION=develop VARIANT=alpine3.12 DATABASE=mariadb
  - VERSION=develop VARIANT=slim-buster DATABASE=postgres
  - VERSION=develop VARIANT=slim-buster DATABASE=mariadb
  - VERSION=v1.3 VARIANT=alpine3.12 DATABASE=postgres
  - VERSION=v1.3 VARIANT=alpine3.12 DATABASE=mariadb
  - VERSION=v1.3 VARIANT=slim-buster DATABASE=postgres
  - VERSION=v1.3 VARIANT=slim-buster DATABASE=mariadb
  - VERSION=v1.4 VARIANT=alpine3.12 DATABASE=postgres
  - VERSION=v1.4 VARIANT=alpine3.12 DATABASE=mariadb
  - VERSION=v1.4 VARIANT=slim-buster DATABASE=postgres
  - VERSION=v1.4 VARIANT=slim-buster DATABASE=mariadb
